<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!--This file includes everyhing that would constitute the robot body -->

    <!-- Contains all mathematically computed intertial values -->
    <xacro:include filename="inertial_macros.xacro"/>

    <!-- This includes all the dimentions of the body so we can change them in one place when differed. -->
    <xacro:include filename="robot_measurements.xacro" />

    <!-- Includes all the materials. -->
    <xacro:include filename="materials.xacro" />

    <!-- BASE LINK -->
    <link name="base_link">
    </link>

    <!-- BASE_FOOTPRINT LINK -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- CASTER WHEEL LINK Front-Left -->
    <joint name="caster_wheel_joint_fl" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_fl"/>
        <origin xyz="${caster_wheel_offset_x} ${caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel_fl">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_fl">
        <material>Gazebo/White</material>
        <!--the lesser the value the lesser the friction-->
        <mu1 value="0.000000000000000001"/>
        <mu2 value="0.000000000000000001"/>
    </gazebo>


    <!-- CASTER WHEEL LINK Front-Right -->
    <joint name="caster_wheel_joint_fr" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_fr"/>
        <origin xyz="${caster_wheel_offset_x} ${-caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel_fr">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_fr">
        <material>Gazebo/White</material>
        <!--the lesser the value the lesser the friction-->
        <mu1 value="0.000000000000000001"/>
        <mu2 value="0.000000000000000001"/>
    </gazebo>


    <!-- CASTER WHEEL LINK Back-Left -->
    <joint name="caster_wheel_joint_bl" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_bl"/>
        <origin xyz="${-caster_wheel_offset_x} ${caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel_bl">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_bl">
        <material>Gazebo/White</material>
        <!--the lesser the value the lesser the friction-->
        <mu1 value="0.000000000000000001"/>
        <mu2 value="0.000000000000000001"/>
    </gazebo>


    <!-- CASTER WHEEL LINK Back-Right -->
    <joint name="caster_wheel_joint_br" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_br"/>
        <origin xyz="${-caster_wheel_offset_x} ${-caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel_br">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_br">
        <material>Gazebo/White</material>
        <!--the lesser the value the lesser the friction-->
        <mu1 value="0.000000000000000001"/>
        <mu2 value="0.000000000000000001"/>
    </gazebo>

    <!-- Top Plate -->
    <joint name="top_plate_joint" type="fixed">
        <parent link="chassis"/>
        <child link="top_plate"/>
        <origin xyz="0 0 ${-wheel_offset_z+chassis_height}"/>
    </joint>
 
    <link name="top_plate">
        <visual>
            <origin xyz="0 0 0.480"/>
            <geometry>
                <box size="0.002 ${chassis_width} 0.960"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0.480"/>
            <geometry>
                <box size="0.002 ${chassis_width} 0.960"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.005" x="0.002" y="${chassis_width}" z="0.960">
            <origin xyz="0 0 0.480" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
 
    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo> 

    <!-- Tray one -->
    <!-- <joint name="tray_one_joint" type="fixed">
        <parent link="top_plate"/>
        <child link="top_plate"/>
        <origin xyz="0 0 0"/>
    </joint>
 
    <link name="top_plate">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="0.002 ${chassis_width} 0.960"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="0.002 ${chassis_width} 0.960"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.005" x="0.002" y="${chassis_width}" z="0.960">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
 
    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>  -->
    
</robot>